/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.*;
import java.nio.file.Paths;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public Quote getRandomQuotes (String path) throws IOException{
        /**
         * Min and max variables to declare the math.random number from 0 to 137 which is the indexes .
         */
        int min = 0 , max = 137;
        /**
         * object of the Gson library to read the json file.
         */
        Gson gson = new Gson();
        /**
         *  Read the json file using buffered reader class
         */
        BufferedReader reader = new BufferedReader(new FileReader(path));
        /**
         * Declare a list of type Quote , call the method fromJson using the gson object , send the reader as an arg with the a TypeToken that holds
         * the List of quotes and .getType to return the type of the list that is required
         */

        List<Quote> quote =  gson.fromJson(reader , new TypeToken<List<Quote>>() {}.getType());
        /**
         * Close the reader .
         */
        reader.close();
        return quote.get((int) (Math.random()*(max-min+1)+min));
    }
    public static void main(String[] args) throws IOException {
       String x = new App().getRandomQuotes("./app/src/main/java/quotes/recentquotes.json").toString();
        System.out.println(new App().getRandomQuotes("./app/src/main/java/quotes/recentquotes.json") );
    }
}
